apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-app-v2
  labels:
    app: my-app
spec:
  # Note that we only start 1 replica of the application
  replicas: 1
  template:
    metadata:
      labels:
        app: my-app
        version: v2.0.0
    spec:
      containers:
      - name: my-app
        image: ludo/k8s-deployment-demo
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: VERSION
          value: v2.0.0
        livenessProbe:
          httpGet:
            path: /-/liveness
            port: 8081
        readinessProbe:
          httpGet:
            path: /-/readiness
            port: 8081
          failureThreshold: 1
          periodSeconds: 1
