apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-app-v2
  labels:
    app: my-app
    version: v2.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
      version: v2.0.0
  template:
    metadata:
      labels:
        app: my-app
        version: v2.0.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9101"
    spec:
      containers:
      - name: my-app
        image: ludo/k8s-deployment-demo
        ports:
        - name: http
          containerPort: 8080
        - name: probe
          containerPort: 8086
        - name: metrics
          containerPort: 9101
        env:
        - name: VERSION
          value: v2.0.0
        livenessProbe:
          httpGet:
            path: /live
            port: probe
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: probe
          periodSeconds: 5
